image: registry.labs.nic.cz/turris/foris-ci

stages:
  - test

test:
  stage: test

  script:
    - git clone https://gitlab.labs.nic.cz/turris/foris-schema.git
    - cd foris-schema
    - python setup.py install
    - cd ..
    - git clone https://gitlab.labs.nic.cz/turris/foris-controller.git
    - cd foris-controller
    - (git checkout refs/remotes/origin/${CI_COMMIT_REF_NAME} || true)
    - python setup.py install
    - cd ..
    - python setup.py install
    - rm -rf {foris-controller,foris-schema}
    - export LD_LIBRARY_PATH=:/usr/local/lib
    - python setup.py test
