#!/bin/sh /etc/rc.common

DEVICE='/dev/ttyUSB9'

# Interface name from /etc/config/network
IFNAME='lte_z'

# Your APN:
APN=''

START=25
STOP=90

start() {
        if [ -e ${DEVICE} ]; then
                echo -ne "AT+CGDCONT=1,\"IP\"\r\n" > ${DEVICE}
                sleep 1
                echo -ne "AT+CGACT=1,1\r\n" > ${DEVICE}
                sleep 2
                echo -ne "AT+DHCPCTRL=1\r\n" > ${DEVICE}
                sleep 2
                ifup $IFNAME
        else
                echo "No such device ${DEVICE}" | logger -t "LTE_Z[$$]" -p info
        fi
}

stop() {
        if [ -e ${DEVICE} ]; then
                ifdown $IFNAME
                sleep 2
                echo -ne "AT+CGACT=0,1\r\n" > ${DEVICE}
        else
                echo "No such device ${DEVICE}" | logger -t "LTE_Z[$$]" -p info
        fi
}

