#!/bin/sh

cat << EOF
config wifi-device  radio0
        option type     mac80211
        option channel  36
        option country  'CZ'
        option hwmode   11a
        option path     'soc/soc:pcie-controller/pci0000:00/0000:00:02.0/0000:02:00.0'
        option htmode   VHT80
        # REMOVE THIS LINE TO ENABLE WIFI:
        option disabled 1

config wifi-iface
        option device   radio0
        option network  lan
        option mode     ap
        option ssid     Turris
        option encryption none

config wifi-device  radio1
        option type     mac80211
        option channel  11
        option country  'CZ'
        option hwmode   11g
        option path     'soc/soc:pcie-controller/pci0000:00/0000:00:03.0/0000:03:00.0'
        option htmode   HT20
        # REMOVE THIS LINE TO ENABLE WIFI:
        option disabled 1

config wifi-iface
        option device   radio1
        option network  lan
        option mode     ap
        option ssid     Turris
        option encryption none

EOF
