#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/config/uci.sh

json_init

case "$1" in
    list)
        echo '{
            "sync_ntp_time": {
                "server": "x.x.x.x"
            },
            "set_local_time": {
                "time_str": "2018-08-08 16:56:40"
            },
            "set_interface_on": {
                "interface": "lte-z/lte-4g",
                "on": "1/0"
            },
            "get_ntp_info": {
            },
            "get_hw_id": {
            },
            "get_host_ip": {
            },
            "set_hw_id": {
                "mac": "aa-bb-cc-dd-ee-ff",
                "imei": "012345678901234"
            },
            "get_lte_z": {
                "type": "LTE-Z",
                "connection_status": "on/off",
                "signal_strength": "17.0",
                "ipaddr": "x.x.x.x",
                "": "x.x.x.x",
                "dns1": "x.x.x.x",
                "dns2": "x.x.x.x",
                "sim_status": "ready",
                "imsi": "imsi",
                "plmn": "plmn",
                "band": "band",
                "rsrq": "rsrq",
                "snr": "snr"
            },
            "get_lte_4g": {
                "type": "LTE-4G",
                "connection_status": "on/off",
                "signal_strength": "17.0",
                "ipaddr": "x.x.x.x",
                "": "x.x.x.x",
                "dns1": "x.x.x.x",
                "dns2": "x.x.x.x",
                "sim_status": "ready",
                "imsi": "imsi",
                "plmn": "plmn",
                "band": "band",
                "rsrq": "rsrq",
                "snr": "snr"
            }
        }'
    ;;
    call)
        case "$2" in
            get_ntp_info)
                server=`uci get system.ntp.server|awk '{print $1}'`
                echo "{
                    'server': '$server'
                }"
            ;;
            sync_ntp_time)
                read input
                logger -t "zl100mt-rpcd" "call" "$2" "$input"
                json_load $input
                json_get_var server server
                TIMEOUT=2 # seconds
                DEFAULT_SERVER=210.72.145.44
                /usr/sbin/ntpdate -s -b -u -t "$TIMEOUT" "$server" 
                uci -q delete system.ntp.server
                uci add_list system.ntp.server=$server
                uci add_list system.ntp.server=$DEFAULT_SERVER
                uci commit system
                /etc/init.d/sysntpd restart
                rc=$?
                ts=`date +%s`
                ts=$((ts * 1000)) # we need ms
                echo "{
                    'rc': 0,
                    'ts': '$ts'
                }"
            ;;
            set_local_time)
                read input
                logger -t "zl100mt-rpcd" "call" "$2" "$input"
                json_load $input
                logger -t "zl100mt-rpcd" "input" "$input"
                json_get_var time_var time_str
                time_var=`echo $time_var | sed -e "s/T/ /"`
                out=`date -s "$time_var"`
                rc=$?
                ts=`date +%s`
                ts=$((ts * 1000)) # ms
                echo "{
                    'rc': 0,
                    'ts': '$ts'
                }"
            ;;
            get_hw_id)
                mac=`hexdump -e '6/1 "%x "' -s 12 -n 6 /sys/bus/i2c/devices/0-0054/eeprom|sed -e "s/ /-/g"`
                imei=`hexdump -e '15/1 "%c"' -s 18 -n 15 /sys/bus/i2c/devices/0-0054/eeprom`

                echo "{
                    'mac': '$mac',
                    'imei': '$imei'
                }"
            ;;
            set_hw_id)
                read input
                logger -t "zl100mt-rpcd" "call" "$2" "$input"
                json_load $input
                json_get_var mac mac
                mac=`echo $mac|sed -e 's/[-:]/\\\x/g'`
                mac="\\x$mac"
                echo -n -e $mac|dd of=/sys/bus/i2c/devices/0-0054/eeprom seek=12 bs=1 count=6

                json_get_var imei imei
                echo -n $imei|dd of=/sys/bus/i2c/devices/0-0054/eeprom seek=18 bs=1 count=15

                echo "{
                    'rc': 'ok'
                }"
            ;;
            get_host_ip)
                ip=`ifconfig br-lan | awk '/inet addr:/{split($2,a,":"); print a[2]}'`
                submask=`ifconfig br-lan | awk '/Mask:/{split($4,a,":"); print a[2]}'`
                echo "{
                    'ip': '$ip',
                    'submask': '$submask'
                }"
            ;;
            get_lte_z)
                data=`gcom -d /dev/ttyUSB9 -s /etc/gcom/zl100mt-zw.gcom`

                json=""
                for kv in $data; do
                    k=`echo $kv|cut -d: -f1`
                    v=`echo $kv|cut -d: -f2`
                    item="'$k'":"'$v'"
                    if [[ -z $json ]]; then
                        json="$item"
                    else
                        json="$json,$item"
                    fi
                done
                json="{ 'type':'LTE-Z', $json }"
                echo $json
            ;;
            get_lte_4g)
                data=`gcom -d /dev/ttyUSB4 -s /etc/gcom/zl100mt-4g.gcom`

                json=""
                for kv in $data; do
                    k=`echo $kv|cut -d: -f1`
                    v=`echo $kv|cut -d: -f2`
                    item="'$k'":"'$v'"
                    if [[ -z $json ]]; then
                        json="$item"
                    else
                        json="$json,$item"
                    fi
                done
                json="{ 'type':'LTE-4G', $json }"
                echo $json
            ;;
            set_interface_on)
                read input
                logger -t "zl100mt-rpcd" "call" "$2" "$input"
                json_load $input
                json_get_var interface interface
                json_get_var on on
                value=$((on==1?0:1))
                uci set network.${interface}.disabled=${value}
                uci commit network
                /etc/init.d/network restart
                json="{ 'rc' : 0 }"
                echo $json
            ;;
        esac
    ;;
esac
