
SOURCES = config.c zl100mt.c
INCDPND = config.h zl100mt.h list.h

zl100mt-app:$(SOURCES) $(INDDPND)
	@echo $(CC) -Wall $(SOURCES) $(CFLAGS) $(LDFLAGS) -o zl100mt-app
	$(CC) -Wall $(SOURCES) $(CFLAGS) $(LDFLAGS) -o zl100mt-app
