
SOURCES = config.c bdrelay.c
INCDPND = config.h bdrelay.h list.h
bdrelay:$(SOURCES) $(INDDPND)
	@echo $(CC) -Wall $(SOURCES) $(CFLAGS) $(LDFLAGS) -o bdrelay
	$(CC) -Wall $(SOURCES) $(CFLAGS) $(LDFLAGS) -o bdrelay
